# Generated by Django 3.1.4 on 2021-01-05 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monstruo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('tamaño_tipo', models.CharField(max_length=200)),
                ('velocidad', models.CharField(max_length=200)),
                ('ca', models.CharField(max_length=200)),
                ('ataquebase_presa', models.CharField(max_length=200)),
                ('ataque', models.CharField(max_length=200)),
                ('ataque_completo', models.CharField(max_length=200)),
                ('espacio_alcance', models.CharField(max_length=200)),
                ('ataques_especiales', models.CharField(max_length=200)),
                ('cualidades_especiales', models.CharField(max_length=200)),
                ('habilidades', models.CharField(max_length=1200)),
                ('dotes', models.CharField(max_length=200)),
                ('entorno', models.CharField(max_length=200)),
                ('organizacion', models.CharField(max_length=200)),
                ('vd', models.CharField(max_length=200)),
                ('tesoro', models.CharField(max_length=200)),
                ('alineamiento', models.CharField(max_length=200)),
                ('avance', models.CharField(max_length=200)),
                ('ajuste_de_nivel', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=20000)),
                ('combate', models.CharField(max_length=20000)),
            ],
        ),
    ]
