# Generated by Django 3.1.4 on 2021-01-07 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monster35', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monstruo',
            old_name='tamaño_tipo',
            new_name='dg_pv',
        ),
        migrations.AddField(
            model_name='monstruo',
            name='iniciativa',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='monstruo',
            name='subtipo',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='monstruo',
            name='tamaño',
            field=models.CharField(default='Mediano', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monstruo',
            name='tipo',
            field=models.CharField(default='Humanoide', max_length=200),
            preserve_default=False,
        ),
    ]
