# Generated by Django 3.1.4 on 2021-01-07 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('descripcion', models.CharField(max_length=200)),
                ('requisito', models.CharField(max_length=200, null=True)),
                ('normal', models.CharField(max_length=200, null=True)),
                ('especial', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
